/*
 Highmaps JS v6.1.1-modified (2018-08-21)

 (c) 2009-2017 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(C){"object"===typeof module&&module.exports?module.exports=C:C(Highcharts)})(function(C){(function(k){k.ajax=function(v){var b=k.merge(!0,{url:!1,type:"GET",dataType:"json",success:!1,error:!1,data:!1,headers:{}},v);v={json:"application/json",xml:"application/xml",text:"text/plain",octet:"application/octet-stream"};var m=new XMLHttpRequest;if(!b.url)return!1;m.open(b.type.toUpperCase(),b.url,!0);m.setRequestHeader("Content-Type",v[b.dataType]||v.text);k.objectEach(b.headers,function(b,k){m.setRequestHeader(k,
b)});m.onreadystatechange=function(){var e;if(4===m.readyState){if(200===m.status){e=m.responseText;if("json"===b.dataType)try{e=JSON.parse(e)}catch(t){b.error&&b.error(m,t);return}return b.success&&b.success(e)}b.error&&b.error(m,m.responseText)}};try{b.data=JSON.stringify(b.data)}catch(e){}m.send(b.data||!0)}})(C);(function(k){var v=k.addEvent,b=k.Chart,m=k.win.document,e=k.each,t=k.objectEach,y=k.pick,A=k.inArray,q=k.isNumber,w=k.merge,l=k.splat,h=k.fireEvent,D=k.some,p,x=function(a,d,c){this.init(a,
d,c)};k.extend(x.prototype,{init:function(a,d,c){var b=a.decimalPoint,g;d&&(this.chartOptions=d);c&&(this.chart=c);"."!==b&&","!==b&&(b=void 0);this.options=a;this.columns=a.columns||this.rowsToColumns(a.rows)||[];this.firstRowAsNames=y(a.firstRowAsNames,this.firstRowAsNames,!0);this.decimalRegex=b&&new RegExp("^(-?[0-9]+)"+b+"([0-9]+)$");this.rawColumns=[];this.columns.length&&(this.dataFound(),g=!0);g||(g=this.fetchLiveData());g||(g=!!this.parseCSV().length);g||(g=!!this.parseTable().length);g||
(g=this.parseGoogleSpreadsheet());!g&&a.afterComplete&&a.afterComplete()},getColumnDistribution:function(){var a=this.chartOptions,d=this.options,c=[],b=function(a){return(k.seriesTypes[a||"line"].prototype.pointArrayMap||[0]).length},g=a&&a.chart&&a.chart.type,f=[],l=[],h=0,d=d&&d.seriesMapping||a&&a.series&&k.map(a.series,function(){return{x:0}})||[],u;e(a&&a.series||[],function(a){f.push(b(a.type||g))});e(d,function(a){c.push(a.x||0)});0===c.length&&c.push(0);e(d,function(c){var d=new p,e=f[h]||
b(g),r=k.seriesTypes[((a&&a.series||[])[h]||{}).type||g||"line"].prototype.pointArrayMap||["y"];d.addColumnReader(c.x,"x");t(c,function(a,c){"x"!==c&&d.addColumnReader(a,c)});for(u=0;u<e;u++)d.hasReader(r[u])||d.addColumnReader(void 0,r[u]);l.push(d);h++});d=k.seriesTypes[g||"line"].prototype.pointArrayMap;void 0===d&&(d=["y"]);this.valueCount={global:b(g),xColumns:c,individual:f,seriesBuilders:l,globalPointArrayMap:d}},dataFound:function(){this.options.switchRowsAndColumns&&(this.columns=this.rowsToColumns(this.columns));
this.getColumnDistribution();this.parseTypes();!1!==this.parsed()&&this.complete()},parseCSV:function(a){function d(a,c,d,f){function g(c){n=a[c];u=a[c-1];h=a[c+1]}function b(a){B.length<q+1&&B.push([a]);B[q][B[q].length-1]!==a&&B[q].push(a)}function e(){k>p||p>m?(++p,z=""):(!isNaN(parseFloat(z))&&isFinite(z)?(z=parseFloat(z),b("number")):isNaN(Date.parse(z))?b("string"):(z=z.replace(/\//g,"-"),b("date")),l.length<q+1&&l.push([]),d||(l[q][c]=z),z="",++q,++p)}var r=0,n="",u="",h="",z="",p=0,q=0;if(a.trim().length&&
"#"!==a.trim()[0]){for(;r<a.length;r++){g(r);if("#"===n){e();return}if('"'===n)for(g(++r);r<a.length&&('"'!==n||'"'===u||'"'===h);){if('"'!==n||'"'===n&&'"'!==u)z+=n;g(++r)}else f&&f[n]?f[n](n,z)&&e():n===t?e():z+=n}e()}}function c(a){var c=0,d=0,b=!1;D(a,function(a,f){var g=!1,b,e,r="";if(13<f)return!0;for(var l=0;l<a.length;l++){f=a[l];b=a[l+1];e=a[l-1];if("#"===f)break;else if('"'===f)if(g){if('"'!==e&&'"'!==b){for(;" "===b&&l<a.length;)b=a[++l];"undefined"!==typeof p[b]&&p[b]++;g=!1}}else g=!0;
else"undefined"!==typeof p[f]?(r=r.trim(),isNaN(Date.parse(r))?!isNaN(r)&&isFinite(r)||p[f]++:p[f]++,r=""):r+=f;","===f&&d++;"."===f&&c++}});b=p[";"]>p[","]?";":",";f.decimalPoint||(f.decimalPoint=c>d?".":",",g.decimalRegex=new RegExp("^(-?[0-9]+)"+f.decimalPoint+"([0-9]+)$"));return b}function b(a,c){var d,b,e=0,r=!1,l=[],u=[],n;if(!c||c>a.length)c=a.length;for(;e<c;e++)if("undefined"!==typeof a[e]&&a[e]&&a[e].length)for(d=a[e].trim().replace(/\//g," ").replace(/\-/g," ").split(" "),b=["","",""],
n=0;n<d.length;n++)n<b.length&&(d[n]=parseInt(d[n],10),d[n]&&(u[n]=!u[n]||u[n]<d[n]?d[n]:u[n],"undefined"!==typeof l[n]?l[n]!==d[n]&&(l[n]=!1):l[n]=d[n],31<d[n]?b[n]=100>d[n]?"YY":"YYYY":12<d[n]&&31>=d[n]?(b[n]="dd",r=!0):b[n].length||(b[n]="mm")));if(r){for(n=0;n<l.length;n++)!1!==l[n]?12<u[n]&&"YY"!==b[n]&&"YYYY"!==b[n]&&(b[n]="YY"):12<u[n]&&"mm"===b[n]&&(b[n]="dd");3===b.length&&"dd"===b[1]&&"dd"===b[2]&&(b[2]="YY");a=b.join("/");return(f.dateFormats||g.dateFormats)[a]?a:(h("deduceDateFailed"),
"YYYY/mm/dd")}return"YYYY/mm/dd"}var g=this,f=a||this.options,e=f.csv,l;a="undefined"!==typeof f.startRow&&f.startRow?f.startRow:0;var u=f.endRow||Number.MAX_VALUE,k="undefined"!==typeof f.startColumn&&f.startColumn?f.startColumn:0,m=f.endColumn||Number.MAX_VALUE,t,q=0,B=[],p={",":0,";":0,"\t":0};l=this.columns=[];e&&f.beforeParse&&(e=f.beforeParse.call(this,e));if(e){e=e.replace(/\r\n/g,"\n").replace(/\r/g,"\n").split(f.lineDelimiter||"\n");if(!a||0>a)a=0;if(!u||u>=e.length)u=e.length-1;f.itemDelimiter?
t=f.itemDelimiter:(t=null,t=c(e));for(var w=0,q=a;q<=u;q++)"#"===e[q][0]?w++:d(e[q],q-a-w);f.columnTypes&&0!==f.columnTypes.length||!B.length||!B[0].length||"date"!==B[0][1]||f.dateFormat||(f.dateFormat=b(l[0]));this.dataFound()}return l},parseTable:function(){var a=this.options,d=a.table,c=this.columns,b=a.startRow||0,g=a.endRow||Number.MAX_VALUE,f=a.startColumn||0,l=a.endColumn||Number.MAX_VALUE;d&&("string"===typeof d&&(d=m.getElementById(d)),e(d.getElementsByTagName("tr"),function(a,d){d>=b&&
d<=g&&e(a.children,function(a,g){("TD"===a.tagName||"TH"===a.tagName)&&g>=f&&g<=l&&(c[g-f]||(c[g-f]=[]),c[g-f][d-b]=a.innerHTML)})}),this.dataFound());return c},fetchLiveData:function(){function a(l){function r(e,r,u){function h(){g&&d.liveDataURL===e&&(d.liveDataTimeout=setTimeout(a,f))}if(!e||0!==e.indexOf("http"))return e&&c.error&&c.error("Invalid URL"),!1;l&&(clearTimeout(d.liveDataTimeout),d.liveDataURL=e);k.ajax({url:e,dataType:u||"json",success:function(a){d&&d.series&&r(a);h()},error:function(a,
d){3>++b&&h();return c.error&&c.error(d,a)}});return!0}r(e.csvURL,function(a){d.update({data:{csv:a}})},"text")||r(e.rowsURL,function(a){d.update({data:{rows:a}})})||r(e.columnsURL,function(a){d.update({data:{columns:a}})})}var d=this.chart,c=this.options,b=0,g=c.enablePolling,f=1E3*(c.dataRefreshRate||2),e=w(c);if(!c||!c.csvURL&&!c.rowsURL&&!c.columnsURL)return!1;1E3>f&&(f=1E3);delete c.csvURL;delete c.rowsURL;delete c.columnsURL;a(!0);return c&&(c.csvURL||c.rowsURL||c.columnsURL)},parseGoogleSpreadsheet:function(){function a(d){var g=
["https://spreadsheets.google.com/feeds/cells",b,f,"public/values?alt\x3djson"].join("/");k.ajax({url:g,dataType:"json",success:function(f){d(f);c.enablePolling&&setTimeout(function(){a(d)},c.dataRefreshRate)},error:function(a,d){return c.error&&c.error(d,a)}})}var d=this,c=this.options,b=c.googleSpreadsheetKey,g=this.chart,f=c.googleSpreadsheetWorksheet||1,l=c.startRow||0,h=c.endRow||Number.MAX_VALUE,u=c.startColumn||0,q=c.endColumn||Number.MAX_VALUE,p=1E3*(c.dataRefreshRate||2);4E3>p&&(p=4E3);b&&
(delete c.googleSpreadsheetKey,a(function(a){var c=[];a=a.feed.entry;var f,b=(a||[]).length,r=0,k,p,m;if(!a||0===a.length)return!1;for(m=0;m<b;m++)f=a[m],r=Math.max(r,f.gs$cell.col);for(m=0;m<r;m++)m>=u&&m<=q&&(c[m-u]=[]);for(m=0;m<b;m++)f=a[m],r=f.gs$cell.row-1,k=f.gs$cell.col-1,k>=u&&k<=q&&r>=l&&r<=h&&(p=f.gs$cell||f.content,f=null,p.numericValue?f=0<=p.$t.indexOf("/")||0<=p.$t.indexOf("-")?p.$t:0<p.$t.indexOf("%")?100*parseFloat(p.numericValue):parseFloat(p.numericValue):p.$t&&p.$t.length&&(f=
p.$t),c[k-u][r-l]=f);e(c,function(a){for(m=0;m<a.length;m++)void 0===a[m]&&(a[m]=null)});g&&g.series?g.update({data:{columns:c}}):(d.columns=c,d.dataFound())}));return!1},trim:function(a,d){"string"===typeof a&&(a=a.replace(/^\s+|\s+$/g,""),d&&/^[0-9\s]+$/.test(a)&&(a=a.replace(/\s/g,"")),this.decimalRegex&&(a=a.replace(this.decimalRegex,"$1.$2")));return a},parseTypes:function(){for(var a=this.columns,d=a.length;d--;)this.parseColumn(a[d],d)},parseColumn:function(a,d){var c=this.rawColumns,b=this.columns,
g=a.length,f,e,h,m,p=this.firstRowAsNames,k=-1!==A(d,this.valueCount.xColumns),t,w=[],x=this.chartOptions,v,y=(this.options.columnTypes||[])[d],x=k&&(x&&x.xAxis&&"category"===l(x.xAxis)[0].type||"string"===y);for(c[d]||(c[d]=[]);g--;)f=w[g]||a[g],h=this.trim(f),m=this.trim(f,!0),e=parseFloat(m),void 0===c[d][g]&&(c[d][g]=h),x||0===g&&p?a[g]=""+h:+m===e?(a[g]=e,31536E6<e&&"float"!==y?a.isDatetime=!0:a.isNumeric=!0,void 0!==a[g+1]&&(v=e>a[g+1])):(h&&h.length&&(t=this.parseDate(f)),k&&q(t)&&"float"!==
y?(w[g]=f,a[g]=t,a.isDatetime=!0,void 0!==a[g+1]&&(f=t>a[g+1],f!==v&&void 0!==v&&(this.alternativeFormat?(this.dateFormat=this.alternativeFormat,g=a.length,this.alternativeFormat=this.dateFormats[this.dateFormat].alternative):a.unsorted=!0),v=f)):(a[g]=""===h?null:h,0!==g&&(a.isDatetime||a.isNumeric)&&(a.mixed=!0)));k&&a.mixed&&(b[d]=c[d]);if(k&&v&&this.options.sort)for(d=0;d<b.length;d++)b[d].reverse(),p&&b[d].unshift(b[d].pop())},dateFormats:{"YYYY/mm/dd":{regex:/^([0-9]{4})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{1,2})$/,
parser:function(a){return Date.UTC(+a[1],a[2]-1,+a[3])}},"dd/mm/YYYY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{4})$/,parser:function(a){return Date.UTC(+a[3],a[2]-1,+a[1])},alternative:"mm/dd/YYYY"},"mm/dd/YYYY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{4})$/,parser:function(a){return Date.UTC(+a[3],a[1]-1,+a[2])}},"dd/mm/YY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{2})$/,parser:function(a){var d=+a[3],d=d>(new Date).getFullYear()-2E3?d+1900:d+2E3;return Date.UTC(d,
a[2]-1,+a[1])},alternative:"mm/dd/YY"},"mm/dd/YY":{regex:/^([0-9]{1,2})[\-\/\.]([0-9]{1,2})[\-\/\.]([0-9]{2})$/,parser:function(a){return Date.UTC(+a[3]+2E3,a[1]-1,+a[2])}}},parseDate:function(a){var d=this.options.parseDate,c,b,g=this.options.dateFormat||this.dateFormat,f;if(d)c=d(a);else if("string"===typeof a){if(g)(d=this.dateFormats[g])||(d=this.dateFormats["YYYY/mm/dd"]),(f=a.match(d.regex))&&(c=d.parser(f));else for(b in this.dateFormats)if(d=this.dateFormats[b],f=a.match(d.regex)){this.dateFormat=
b;this.alternativeFormat=d.alternative;c=d.parser(f);break}f||(f=Date.parse(a),"object"===typeof f&&null!==f&&f.getTime?c=f.getTime()-6E4*f.getTimezoneOffset():q(f)&&(c=f-6E4*(new Date(f)).getTimezoneOffset()))}return c},rowsToColumns:function(a){var d,c,b,g,f;if(a)for(f=[],c=a.length,d=0;d<c;d++)for(g=a[d].length,b=0;b<g;b++)f[b]||(f[b]=[]),f[b][d]=a[d][b];return f},parsed:function(){if(this.options.parsed)return this.options.parsed.call(this,this.columns)},getFreeIndexes:function(a,d){var c,b=[],
g=[],f;for(c=0;c<a;c+=1)b.push(!0);for(a=0;a<d.length;a+=1)for(f=d[a].getReferencedColumnIndexes(),c=0;c<f.length;c+=1)b[f[c]]=!1;for(c=0;c<b.length;c+=1)b[c]&&g.push(c);return g},complete:function(){var a=this.columns,d,c=this.options,b,g,f,e,l=[],h;if(c.complete||c.afterComplete){if(this.firstRowAsNames)for(f=0;f<a.length;f++)a[f].name=a[f].shift();b=[];g=this.getFreeIndexes(a.length,this.valueCount.seriesBuilders);for(f=0;f<this.valueCount.seriesBuilders.length;f++)h=this.valueCount.seriesBuilders[f],
h.populateColumns(g)&&l.push(h);for(;0<g.length;){h=new p;h.addColumnReader(0,"x");f=A(0,g);-1!==f&&g.splice(f,1);for(f=0;f<this.valueCount.global;f++)h.addColumnReader(void 0,this.valueCount.globalPointArrayMap[f]);h.populateColumns(g)&&l.push(h)}0<l.length&&0<l[0].readers.length&&(h=a[l[0].readers[0].columnIndex],void 0!==h&&(h.isDatetime?d="datetime":h.isNumeric||(d="category")));if("category"===d)for(f=0;f<l.length;f++)for(h=l[f],g=0;g<h.readers.length;g++)"x"===h.readers[g].configName&&(h.readers[g].configName=
"name");for(f=0;f<l.length;f++){h=l[f];g=[];for(e=0;e<a[0].length;e++)g[e]=h.read(a,e);b[f]={data:g};h.name&&(b[f].name=h.name);"category"===d&&(b[f].turboThreshold=0)}a={series:b};d&&(a.xAxis={type:d},"category"===d&&(a.xAxis.uniqueNames=!1));c.complete&&c.complete(a);c.afterComplete&&c.afterComplete(a)}},update:function(a,d){var c=this.chart;a&&(a.afterComplete=function(a){a.xAxis&&c.xAxis[0]&&a.xAxis.type===c.xAxis[0].options.type&&delete a.xAxis;c.update(a,d,!0)},w(!0,this.options,a),this.init(this.options))}});
k.Data=x;k.data=function(a,d){return new x(a,d)};v(b,"init",function(a){var d=this,c=a.args[0],b=a.args[1];c&&c.data&&!d.hasDataDef&&(d.hasDataDef=!0,d.data=new x(k.extend(c.data,{afterComplete:function(a){var f,e;if(c.hasOwnProperty("series"))if("object"===typeof c.series)for(f=Math.max(c.series.length,a&&a.series?a.series.length:0);f--;)e=c.series[f]||{},c.series[f]=w(e,a&&a.series?a.series[f]:{});else delete c.series;c=w(a,c);d.init(c,b)}}),c,d),a.preventDefault())});p=function(){this.readers=
[];this.pointIsArray=!0};p.prototype.populateColumns=function(a){var d=!0;e(this.readers,function(c){void 0===c.columnIndex&&(c.columnIndex=a.shift())});e(this.readers,function(a){void 0===a.columnIndex&&(d=!1)});return d};p.prototype.read=function(a,d){var c=this.pointIsArray,b=c?[]:{},g;e(this.readers,function(f){var e=a[f.columnIndex][d];c?b.push(e):0<f.configName.indexOf(".")?k.Point.prototype.setNestedProperty(b,e,f.configName):b[f.configName]=e});void 0===this.name&&2<=this.readers.length&&
(g=this.getReferencedColumnIndexes(),2<=g.length&&(g.shift(),g.sort(function(a,c){return a-c}),this.name=a[g.shift()].name));return b};p.prototype.addColumnReader=function(a,b){this.readers.push({columnIndex:a,configName:b});"x"!==b&&"y"!==b&&void 0!==b&&(this.pointIsArray=!1)};p.prototype.getReferencedColumnIndexes=function(){var a,b=[],c;for(a=0;a<this.readers.length;a+=1)c=this.readers[a],void 0!==c.columnIndex&&b.push(c.columnIndex);return b};p.prototype.hasReader=function(a){var b,c;for(b=0;b<
this.readers.length;b+=1)if(c=this.readers[b],c.configName===a)return!0}})(C);(function(k){var v=k.each;k.wrap(k.Data.prototype,"init",function(b,m){b.call(this,m);m.svg&&this.loadSVG()});k.extend(k.Data.prototype,{pathToArray:function(b,m){var e=0,k=0,v,A,q=[0,0],w=[0,0],l,h,D=function(b,e){return[e.a*b[0]+e.c*b[1]+e.e,e.b*b[0]+e.d*b[1]+e.f]};b=b.replace(/[0-9]+e-?[0-9]+/g,function(b){return+b}).replace(/([A-Za-z])/g," $1 ").replace(/-/g," -").replace(/^\s*/,"").replace(/\s*$/,"").replace(/\s+/g,
" ").split(/[ ,]+/);if(1===b.length)return[];for(e=0;e<b.length;e++)if(v=/[a-zA-Z]/.test(b[e])){h=b[e];A=2;if("c"===h||"C"===h)A=6;"m"===h?w=[parseFloat(b[e+1])+w[0],parseFloat(b[e+2])+w[1]]:"M"===h&&(w=[parseFloat(b[e+1]),parseFloat(b[e+2])]);if("m"===h||"l"===h||"c"===h)b[e]=h.toUpperCase(),l=!0;else if("M"===h||"L"===h||"C"===h)l=!1;else if("h"===h)l=!0,b[e]="L",b.splice(e+2,0,0);else if("v"===h)l=!0,b[e]="L",b.splice(e+1,0,0);else if("s"===h)l=!0,b[e]="L",b.splice(e+1,2);else if("S"===h)l=!1,
b[e]="L",b.splice(e+1,2);else if("H"===h||"h"===h)l=!1,b[e]="L",b.splice(e+2,0,q[1]);else if("V"===h||"v"===h)l=!1,b[e]="L",b.splice(e+1,0,q[0]);else if("z"===h||"Z"===h)q=w}else b[e]=parseFloat(b[e]),l&&(b[e]+=q[k%2]),1===k%2&&m&&(!l||"m"===h&&3>e)&&(v=D([b[e-1],b[e]],m),b[e-1]=v[0],b[e]=v[1]),k===A-1?(q=[b[e-1],b[e]],k=0):k+=1;"number"===typeof b[0]&&4<=b.length&&(b.unshift("M"),b.splice(3,0,"L"));return b},pathToString:function(b){v(b,function(b){var e=b.path,e=e.join(","),e=e.replace(/,?([a-zA-Z]),?/g,
"$1");b.path=e});return b},roundPaths:function(b,m){var e=k.seriesTypes.map.prototype,t,y;t={xAxis:{translate:k.Axis.prototype.translate,options:{},minPixelPadding:0},yAxis:{translate:k.Axis.prototype.translate,options:{},minPixelPadding:0}};e.getBox.call(t,b);y=Math.max(t.maxX-t.minX,t.maxY-t.minY);m=m||1E3;y=m/y;t.xAxis.transA=t.yAxis.transA=y;t.xAxis.len=t.yAxis.len=m;t.xAxis.min=t.minX;t.yAxis.min=(t.minY+m)/y;v(b,function(b){var k,m;b.path=m=e.translatePath.call(t,b.path,!0);for(k=m.length;k--;)"number"===
typeof m[k]&&(m[k]=Math.round(m[k]));delete b._foundBox});return b},loadSVG:function(){function b(b){return Array.prototype.slice.call(b.getElementsByTagName("path")).concat(Array.prototype.slice.call(b.getElementsByTagName("polygon"))).concat(Array.prototype.slice.call(b.getElementsByTagName("rect")))}function k(b){if("path"===b.nodeName)return b.getAttribute("d");if("polygon"===b.nodeName)return b.getAttribute("points");if("rect"===b.nodeName){var e=+b.getAttribute("x"),l=+b.getAttribute("y"),k=
+b.getAttribute("width");b=+b.getAttribute("height");return[e,l,e+k,l,e+k,l+b,e,l+b,e,l].join(" ")}}function e(b){b=b.getCTM();if(!isNaN(b.f))return b}function t(b){var e=b.getElementsByTagName("desc");return(e=e[0]&&e[0].getElementsByTagName("name"))&&e[0]&&e[0].innerText||b.getAttribute("inkscape:label")||b.getAttribute("id")||b.getAttribute("class")}function y(b){return!/fill[\s]?\:[\s]?none/.test(b.getAttribute("style"))&&"none"!==b.getAttribute("fill")}function A(l){var h=[],m,p,x,a,d;q.$frame=
q.$frame||$("\x3cdiv\x3e").css({position:"absolute",top:"-9999em"}).appendTo($(document.body));q.$frame.html(l);l=$("svg",q.$frame)[0];l.removeAttribute("viewBox");p=b(l);v(["defs","clipPath"],function(a){v(l.getElementsByTagName(a),function(a){v(a.getElementsByTagName("path"),function(a){a.skip=!0})})});v(p,function(a,b){if(!a.skip){var c=[];0<b&&a.parentNode!==m&&(d=!0);for(m=a.parentNode;a;)c.push(a),a=a.parentNode;c.reverse();if(x)for(a=0;a<x.length;a++)x[a]!==c[a]&&(x=x.slice(0,a));else x=c}});
a=x[x.length-1];d&&v(a.getElementsByTagName("g"),function(a){var c=[],d;v(b(a),function(a){a.skip||(c=c.concat(q.pathToArray(k(a),e(a))),y(a)&&(d=!0),a.skip=!0)});h.push({name:t(a),path:c,hasFill:d})});v(p,function(a){a.skip||h.push({name:t(a),path:q.pathToArray(k(a),e(a)),hasFill:y(a)})});q.roundPaths(h);w.complete({series:[{data:h}]})}var q=this,w=this.options;-1!==w.svg.indexOf("\x3csvg")?A(w.svg):jQuery.ajax({url:w.svg,dataType:"text",success:A})}})})(C)});