/*
 Highcharts JS v6.1.1-modified (2018-08-21)

 (c) 2016 Highsoft AS
 Authors: Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(m){"object"===typeof module&&module.exports?module.exports=m:m(Highcharts)})(function(m){var I=function(){return function(a){var q=this,e=q.graphic,z=a.animate,v=a.attr,r=a.onComplete,l=a.css,x=a.group,m=a.renderer,w=a.shapeArgs;a=a.shapeType;q.shouldDraw()?(e||(q.graphic=e=m[a](w).add(x)),e.css(l).attr(v).animate(z,void 0,r)):e&&e.animate(z,void 0,function(){q.graphic=e=e.destroy();"function"===typeof r&&r()});e&&e.addClass(q.getClassName(),!0)}}(),J=function(a){var q=a.deg2rad,e=a.find,
m=a.isArray,v=a.isNumber,r=a.map,l=a.reduce,x=function(c,b){b=v(b)?b:14;b=Math.pow(10,b);return Math.round(c*b)/b},B=function(c,b){var n=b[0]-c[0];c=b[1]-c[1];return[[-c,n],[c,-n]]},w=function(c,b){c=r(c,function(c){return c[0]*b[0]+c[1]*b[1]});return{min:Math.min.apply(this,c),max:Math.max.apply(this,c)}},y=function(c,b){var n=c[0];c=c[1];var a=q*-b;b=Math.cos(a);a=Math.sin(a);return[x(n*b-c*a),x(n*a+c*b)]},F=function(c,b,a){c=y([c[0]-b[0],c[1]-b[1]],a);return[c[0]+b[0],c[1]+b[1]]},G=function(c){var b,
a=c.axes;m(a)||(a=[],b=b=c.concat([c[0]]),l(b,function(b,c){var n=B(b,c)[0];e(a,function(b){return b[0]===n[0]&&b[1]===n[1]})||a.push(n);return c}),c.axes=a);return a},C=function(c,b){c=G(c);b=G(b);return c.concat(b)};return{getBoundingBoxFromPolygon:function(c){return l(c,function(b,c){var a=c[0];c=c[1];b.left=Math.min(a,b.left);b.right=Math.max(a,b.right);b.bottom=Math.max(c,b.bottom);b.top=Math.min(c,b.top);return b},{left:Number.MAX_SAFE_INTEGER,right:Number.MIN_SAFE_INTEGER,bottom:Number.MIN_SAFE_INTEGER,
top:Number.MAX_SAFE_INTEGER})},getPolygon:function(c,b,a,e,l){var n=[c,b],p=c-a/2;c+=a/2;a=b-e/2;b+=e/2;return r([[p,a],[c,a],[c,b],[p,b]],function(c){return F(c,n,-l)})},isPolygonsColliding:function(c,b){var a=C(c,b);return!e(a,function(a){var e=w(c,a);a=w(b,a);return!!(a.min>e.max||a.max<e.min)})},movePolygon:function(c,a,e){return r(e,function(b){return[b[0]+c,b[1]+a]})},rotate2DToOrigin:y,rotate2DToPoint:F}}(m);(function(a,m,e){var q=a.each,v=a.extend,r=a.isArray,l=a.isNumber,x=a.isObject,B=a.map,
w=a.find,y=a.reduce,F=e.getBoundingBoxFromPolygon,G=e.getPolygon,C=e.isPolygonsColliding,c=e.movePolygon,b=a.Series,n=function(h,f){var d=!1,a=h.rect,c=h.polygon,b=h.lastCollidedWith,e=function(f){var d;d=f.rect;(d=!(d.left>a.right||d.right<a.left||d.top>a.bottom||d.bottom<a.top))&&(h.rotation%90||f.roation%90)&&(d=C(c,f.polygon));return d};b&&((d=e(b))||delete h.lastCollidedWith);d||(d=!!w(f,function(d){var f=e(d);f&&(h.lastCollidedWith=d);return f}));return d},p=function(h){var f=4*h,d=Math.ceil((Math.sqrt(f)-
1)/2),a=2*d+1,c=Math.pow(a,2),b=!1,a=a-1;1E4>=h&&("boolean"===typeof b&&f>=c-a&&(b={x:d-(c-f),y:-d}),c-=a,"boolean"===typeof b&&f>=c-a&&(b={x:-d,y:-d+(c-f)}),c-=a,"boolean"===typeof b&&(b=f>=c-a?{x:-d+(c-f),y:d}:{x:d,y:d-(c-f-a)}),b.x*=5,b.y*=5);return b},I=function(a,f,d){var b=2*Math.max(Math.abs(d.top),Math.abs(d.bottom));d=2*Math.max(Math.abs(d.left),Math.abs(d.right));return Math.min(0<d?1/d*a:1,0<b?1/b*f:1)},J=function(a,b,d){d=y(d,function(a,b){b=b.dimensions;var d=Math.max(b.width,b.height);
a.maxHeight=Math.max(a.maxHeight,b.height);a.maxWidth=Math.max(a.maxWidth,b.width);a.area+=d*d;return a},{maxHeight:0,maxWidth:0,area:0});d=Math.max(d.maxHeight,d.maxWidth,.85*Math.sqrt(d.area));var c=a>b?a/b:1;a=b>a?b/a:1;return{width:d*c,height:d*a,ratioX:c,ratioY:a}},D=function(a,b,d,c){var f=!1;l(a)&&l(b)&&l(d)&&l(c)&&-1<a&&-1<b&&c>d&&(f=d+b%a*((c-d)/(a-1)));return f},L=function(a,b){var d=B(Array(1E4),function(d,c){return a(c+1,b)});return function(a){return 1E4>=a?d[a-1]:!1}},M=function(a,b){var d=
b.width/2,c=-(b.height/2),f=b.height/2;return!(-(b.width/2)<a.left&&d>a.right&&c<a.top&&f>a.bottom)};a.seriesType("wordcloud","column",{animation:{duration:500},borderWidth:0,clip:!1,colorByPoint:!0,minFontSize:1,maxFontSize:25,placementStrategy:"center",rotation:{from:0,orientations:2,to:90},showInLegend:!1,spiral:"rectangular",style:{fontFamily:"sans-serif",fontWeight:"900"},tooltip:{followPointer:!0,pointFormat:'\x3cspan style\x3d"color:{point.color}"\x3e\u25cf\x3c/span\x3e {series.name}: \x3cb\x3e{point.weight}\x3c/b\x3e\x3cbr/\x3e'}},
{animate:b.prototype.animate,bindAxes:function(){var a={endOnTick:!1,gridLineWidth:0,lineWidth:0,maxPadding:0,startOnTick:!1,title:null,tickPositions:[]};b.prototype.bindAxes.call(this);v(this.yAxis.options,a);v(this.xAxis.options,a)},deriveFontSize:function(a,b,c){a=l(a)?a:0;b=l(b)?b:1;c=l(c)?c:1;return Math.floor(Math.max(c,a*b))},drawPoints:function(){var a=this,b=a.hasRendered,d=a.xAxis,e=a.yAxis,m=a.group,t=a.options,r=t.animation,w=a.chart.renderer,p=w.text().add(m),y=[],C=a.placementStrategy[t.placementStrategy],
B,D=t.rotation,z=a.points.map(function(a){return a.weight}),K=Math.max.apply(null,z),H=a.points.sort(function(a,b){return b.weight-a.weight}),A;q(H,function(b){var c=a.deriveFontSize(1/K*b.weight,t.maxFontSize,t.minFontSize),c=v({fontSize:c+"px"},t.style);p.css(c).attr({x:0,y:0,text:b.name});c=p.getBBox(!0);b.dimensions={height:c.height,width:c.width}});A=J(d.len,e.len,H);B=L(a.spirals[t.spiral],{field:A});q(H,function(d){var f=a.deriveFontSize(1/K*d.weight,t.maxFontSize,t.minFontSize),f=v({fontSize:f+
"px",fill:d.color},t.style),e=C(d,{data:H,field:A,placed:y,rotation:D}),h={align:"center","alignment-baseline":"middle",x:e.x,y:e.y,text:d.name,rotation:e.rotation},g=G(e.x,e.y,d.dimensions.width,d.dimensions.height,e.rotation),k=F(g),e=e.rotation,q=A,p=1,u={x:0,y:0},E=d.rect=v({},k);d.polygon=g;for(d.rotation=e;!1!==u&&(n(d,y)||M(E,q));)u=B(p),x(u)&&(E.left=k.left+u.x,E.right=k.right+u.x,E.top=k.top+u.y,E.bottom=k.bottom+u.y,d.polygon=c(u.x,u.y,g)),p++;var g=u,z;if(x(g)){h.x+=g.x;h.y+=g.y;k.left+=
g.x;k.right+=g.x;k.top+=g.y;k.bottom+=g.y;g=A;if(!l(g.left)||g.left>k.left)g.left=k.left;if(!l(g.right)||g.right<k.right)g.right=k.right;if(!l(g.top)||g.top>k.top)g.top=k.top;if(!l(g.bottom)||g.bottom<k.bottom)g.bottom=k.bottom;A=g;y.push(d);d.isNull=!1}else d.isNull=!0;r&&(z={x:h.x,y:h.y},b?(delete h.x,delete h.y):(h.x=0,h.y=0));d.draw({animate:z,attr:h,css:f,group:m,renderer:w,shapeArgs:void 0,shapeType:"text"})});p=p.destroy();d=I(d.len,e.len,A);a.group.attr({scaleX:d,scaleY:d})},hasData:function(){return x(this)&&
!0===this.visible&&r(this.points)&&0<this.points.length},placementStrategy:{random:function(a,b){var c=b.field;b=b.rotation;return{x:Math.round(c.width*(Math.random()+.5)/2)-c.width/2,y:Math.round(c.height*(Math.random()+.5)/2)-c.height/2,rotation:D(b.orientations,a.index,b.from,b.to)}},center:function(a,b){b=b.rotation;return{x:0,y:0,rotation:D(b.orientations,a.index,b.from,b.to)}}},pointArrayMap:["weight"],spirals:{archimedean:function(a,b){var c=b.field;b=!1;var c=c.width*c.width+c.height*c.height,
e=.8*a;1E4>=a&&(b={x:e*Math.cos(e),y:e*Math.sin(e)},Math.min(Math.abs(b.x),Math.abs(b.y))<c||(b=!1));return b},rectangular:function(a,b){a=p(a,b);b=b.field;a&&(a.x*=b.ratioX,a.y*=b.ratioY);return a},square:p},utils:{getRotation:D,isPolygonsColliding:C,rotate2DToOrigin:e.rotate2DToOrigin,rotate2DToPoint:e.rotate2DToPoint},getPlotBox:function(){var a=this.chart,b=a.inverted,c=this[b?"yAxis":"xAxis"],b=this[b?"xAxis":"yAxis"];return{translateX:(c?c.left:a.plotLeft)+(c?c.len:a.plotWidth)/2,translateY:(b?
b.top:a.plotTop)+(b?b.len:a.plotHeight)/2,scaleX:1,scaleY:1}}},{draw:m,shouldDraw:function(){return!this.isNull},weight:1})})(m,I,J)});